# Note: jobs of ci.yml and ci-dispatch.yml should be in sync
name: ci-dispatch

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner OS'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'

env:
  COMMON_SCRIPTS_ROOT: "${{ github.workspace }}"

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: CI on ${{ inputs.runner }}
    runs-on: ${{ inputs.runner }}
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
        if: startsWith(matrix.runner, 'ubuntu')
      - run: ./ci/prerequisite.sh
      - run: ./ci/ci-common-scripts.sh
