# Note: jobs of ci.yml and ci-dispatch.yml should be in sync
name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  COMMON_SCRIPTS_ROOT: "${{ github.workspace }}"

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: CI on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v4
      - run: ./ci/prerequisite.sh
      - run: ./ci/ci-common-scripts.sh
