name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner OS'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
          - 'macos-13'

env:
  COMMON_SCRIPTS_ROOT: "${{ github.workspace }}"

defaults:
  run:
    shell: bash

jobs:
  ci-primary-linux:
    runs-on: ${{ inputs.runner || matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v3
      - run: ./ci/ci-common-scripts.sh
